name: Python application test with Github Actions

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install Pre-commit
        run: |
          make install
          pre-commit install
      - name: Run Pre-commit
        uses: pre-commit/action@v3.0.0
  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5
          architecture: x64
          cache: 'pip'
      - name: Install dependencies
        run: |
          make install
          python -m textblob.download_corpora
      - name: Build Container
        run: |
          make build
